// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVaeeLmw-HSJX33iIXMGo3_ISZV4qGfHM',
    appId: '1:831475816997:web:f9e357e491284f3da63dcc',
    messagingSenderId: '831475816997',
    projectId: 'kkc-officiel',
    authDomain: 'kkc-officiel.firebaseapp.com',
    storageBucket: 'kkc-officiel.firebasestorage.app',
    measurementId: 'G-F09KWZ788Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBroIOXePBpApQhwX2Lc8_UKDL28OTq1Zs',
    appId: '1:831475816997:android:0bd4a8c01d4c9339a63dcc',
    messagingSenderId: '831475816997',
    projectId: 'kkc-officiel',
    storageBucket: 'kkc-officiel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKpZ2CKGN5I1ZB60A_dVanHZxyhliKbEk',
    appId: '1:831475816997:ios:040b2d2163044658a63dcc',
    messagingSenderId: '831475816997',
    projectId: 'kkc-officiel',
    storageBucket: 'kkc-officiel.firebasestorage.app',
    iosBundleId: 'com.example.kkc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKpZ2CKGN5I1ZB60A_dVanHZxyhliKbEk',
    appId: '1:831475816997:ios:040b2d2163044658a63dcc',
    messagingSenderId: '831475816997',
    projectId: 'kkc-officiel',
    storageBucket: 'kkc-officiel.firebasestorage.app',
    iosBundleId: 'com.example.kkc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVaeeLmw-HSJX33iIXMGo3_ISZV4qGfHM',
    appId: '1:831475816997:web:e0ece3aa23561bb7a63dcc',
    messagingSenderId: '831475816997',
    projectId: 'kkc-officiel',
    authDomain: 'kkc-officiel.firebaseapp.com',
    storageBucket: 'kkc-officiel.firebasestorage.app',
    measurementId: 'G-JCFSSHRLVY',
  );
}
